# Generated by Django 3.2.25 on 2024-03-26 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('price', models.FloatField()),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_as_arrival', to='app.busstation')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_as_departure', to='app.busstation')),
            ],
        ),
    ]
