# Generated by Django 3.2.25 on 2024-03-30 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20240326_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='phone_number',
            field=models.CharField(default=89284323445, max_length=10, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='busstation',
            name='station_name',
            field=models.CharField(max_length=30, verbose_name='Станция'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='date_of_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='passport',
            field=models.CharField(max_length=10, verbose_name='Пасспорт'),
        ),
        migrations.AlterField(
            model_name='route',
            name='arrival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_as_arrival', to='app.busstation', verbose_name='Прибытие'),
        ),
        migrations.AlterField(
            model_name='route',
            name='arrival_time',
            field=models.DateTimeField(verbose_name='Время прибытия'),
        ),
        migrations.AlterField(
            model_name='route',
            name='departure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_as_departure', to='app.busstation', verbose_name='Отправление'),
        ),
        migrations.AlterField(
            model_name='route',
            name='departure_time',
            field=models.DateTimeField(verbose_name='Время отправления'),
        ),
        migrations.AlterField(
            model_name='route',
            name='passengers',
            field=models.ManyToManyField(to='app.Passenger', verbose_name='Пассажиры'),
        ),
        migrations.AlterField(
            model_name='route',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
    ]
